<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_mainframe</name>
   <tag></tag>
   <elementGuidId>1a9b5695-d099-47bf-af77-5a5e2a9e7c16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mainframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='mainframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>ffd0e657-d3f8-470f-bd1d-4870447c5faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1bee3a71-f7c3-4228-9cd9-c4a476b657ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>01b5dd00-2188-4783-9b76-9eceebdbffab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mainframe</value>
      <webElementGuid>89b2143b-6134-4e5f-9d44-e00239d720ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>89667745-90d0-4ff3-b484-5e9d6fc06b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/mainmenu_base//pages/login</value>
      <webElementGuid>2cc98772-162f-490e-ae16-24678652f609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainframe&quot;)</value>
      <webElementGuid>60b68511-c7f8-479e-80e7-ab583a10c350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='mainframe']</value>
      <webElementGuid>36420904-6edc-4855-960f-d8ef7967c2d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8b0a4f30-900b-4304-b3ad-4006d8632b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'mainframe' and @src = '/mainmenu_base//pages/login']</value>
      <webElementGuid>0658c762-8825-4e9e-8b96-517e2d3993bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
